name: cifar10_pytorch_const
hyperparameters:
  learning_rate: 0.02
  learning_rate_decay: 0
  cnv_out_ch_0: 64
  cnv_stride_0: 1
  cnv_pool_0: False
  cnv_out_ch_1: 64
  cnv_stride_1: 1
  cnv_pool_1: True
  cnv_out_ch_2: 128
  cnv_stride_2: 1
  cnv_pool_2: False
  cnv_out_ch_3: 128
  cnv_stride_3: 1
  cnv_pool_3: True
  cnv_out_ch_4: 256
  cnv_stride_4: 1
  cnv_pool_4: False
  cnv_out_ch_5: 256
  cnv_stride_5: 1
  cnv_pool_5: False
  int_fc_feat_1: 512
  int_fc_feat_2: 512
  weight_bit_width: 1
  act_bit_width: 1
  pool_size: 2
  kern_size: 3
  global_batch_size: 100
profiling:
  enabled: true
  begin_on_batch: 0
  end_after_batch: 32000
records_per_epoch: 50000
searcher:
  name: single
  metric: validation_error
  max_length:
    epochs: 5000
entrypoint: model_def:CIFARTrial
min_validation_period:
  epochs: 1
environment:
  image: "determinedai/environments:cuda-11.0-pytorch-1.7-lightning-1.2-tf-2.4-gpu-0.16.0"
checkpoint_storage:
  type: shared_fs
  host_path: /xilinx/scratch/determined
resources:
  slots_per_trial: 1
  max_slots: 1
